version: "3.8"

services:
  service_postgres:
    image: postgres:latest
    restart: always
    container_name: container_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data

  service_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container_pgadmin
    ports:
      - 8081:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - service_postgres

volumes:
  vapp:
    name: vapp
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga
